// tanstack-query-react/workshops/05_optimistic_updates/src/components/NewIssueForm.tsx
import { useState, type FormEvent } from 'react';
import { useCreateIssue } from '../queries/issues';

export function NewIssueForm() {
  const [title, setTitle] = useState('');
  const { mutate, isPending, error } = useCreateIssue();

  function submit(event: FormEvent<HTMLFormElement>): void {
    event.preventDefault();
    mutate({ title }, { onSuccess: () => setTitle('') });
  }

  return (
    <>
      {/* TODO (step 3): while `isPending`, show what the user sent — greyed out:
          <ul className="issues">
            <li className="pending" data-testid="pending-issue">{variables.title}</li>
          </ul> */}

      <form className="row" onSubmit={submit}>
        <input
          aria-label="Title of the new issue"
          placeholder="Title of the new issue"
          data-testid="new-title"
          value={title}
          onChange={(event) => setTitle(event.target.value)}
        />
        <button type="submit" data-testid="create-submit" disabled={isPending}>
          {isPending ? 'Creating…' : 'Create'}
        </button>
        {error && (
          <p className="error" data-testid="create-error">
            {error.message}
          </p>
        )}
      </form>
    </>
  );
}

// tanstack-query-angular/workshops/05_optimistic_updates/src/app/issues/new-issue-form.ts
import { Component, signal } from '@angular/core';
import { injectCreateIssue } from './issue-mutations';

@Component({
  selector: 'app-new-issue-form',
  template: `
    <form class="toolbar" (submit)="submit($event)">
      <input
        #titleInput
        data-testid="new-title"
        placeholder="What is broken?"
        aria-label="Title of the new issue"
        [value]="title()"
        (input)="title.set(titleInput.value)"
      />
      <button type="submit" data-testid="create-submit" [disabled]="createIssue.isPending()">Create</button>
    </form>
    @if (createIssue.isError()) {
      <p class="error" data-testid="create-error">{{ createIssue.error().message }}</p>
    }
    <!-- TODO (step 3): while the creation is pending, show what was SENT —
         createIssue.variables() — in a greyed-out <li data-testid="pending-issue">. -->
  `,
})
export class NewIssueForm {
  protected readonly title = signal('');
  protected readonly createIssue = injectCreateIssue();

  protected submit(event: Event): void {
    event.preventDefault();
    this.createIssue.mutate(this.title(), {
      onSuccess: () => this.title.set(''),
    });
  }
}
