// tanstack-query-vue/workshops/02_query_configuration/src/components/IssueDetail.vue
<script setup lang="ts">
import { useQuery } from '@tanstack/vue-query';
import { issueQuery } from '@/queries/issues';

const props = defineProps<{ issueId: number | undefined }>();

// Two bugs, both in the Network panel:
// - nothing is selected on load, yet `GET /issues/undefined` leaves (and fails,
//   and is retried): the query runs whatever the selection;
// - select an issue: the panel stays empty for a full round trip, though the
//   list on its left already knows the title.
//
// TODO (step 2) — no request while nothing is selected (`skipToken` in
// `issueQuery`, or `enabled`).
// TODO (step 3) — `placeholderData`: the summary of the issue, found in the
// cached lists (`queryClient.getQueriesData({ queryKey: issueKeys.lists() })`).
// Show `detail-description` only once the REAL detail arrived
// (`isPlaceholderData`).
const { data: issue, error } = useQuery(() => issueQuery(props.issueId as number));
</script>

<template>
  <section>
    <h2>Detail</h2>
    <p v-if="issueId === undefined" class="muted" data-testid="detail-empty">Select an issue to see its description.</p>
    <p v-else-if="error" class="error">{{ error.message }}</p>
    <p v-else-if="!issue" class="muted">Loading…</p>
    <template v-else>
      <h3 data-testid="detail-title">#{{ issue.id }} {{ issue.title }}</h3>
      <p class="muted">{{ issue.status }} · {{ issue.assignee ?? 'unassigned' }} · {{ issue.commentCount }} comment(s)</p>
      <p data-testid="detail-description">{{ issue.description }}</p>
    </template>
  </section>
</template>

// tanstack-query-angular/workshops/02_query_configuration/src/app/issues/issue-detail.ts
import { Component, input } from '@angular/core';
import { injectQuery } from '@tanstack/angular-query-experimental';
import { issueDetailQuery } from './issue-queries';

@Component({
  selector: 'app-issue-detail',
  template: `
    <aside class="detail">
      @if (issueId() === undefined) {
        <p class="muted" data-testid="detail-empty">Select an issue to see its details.</p>
      } @else if (detail.data(); as issue) {
        <h2 data-testid="detail-title">#{{ issue.id }} {{ issue.title }}</h2>
        <p class="muted">{{ issue.status }} · {{ issue.assignee ?? 'unassigned' }} · {{ issue.commentCount }} comment(s)</p>
        <!-- TODO (step 3): while the data is a placeholder (isPlaceholderData()),
             there is no description to show yet. -->
        <p data-testid="detail-description">{{ issue.description }}</p>
      } @else if (detail.isError()) {
        <p class="error">{{ detail.error().message }}</p>
      } @else {
        <p class="muted">Loading…</p>
      }
    </aside>
  `,
})
export class IssueDetail {
  readonly issueId = input<number>();

  // The `as number` silences TypeScript, not the request: with nothing
  // selected, this sends `GET /issues/undefined`. Read the Network panel.
  // TODO (step 2): no request at all until an issue is selected.
  // TODO (step 3): `placeholderData` — the summary from the list cache, so the
  // title shows at once. Why not `initialData`?
  protected readonly detail = injectQuery(() => issueDetailQuery(this.issueId() as number));
}
