// tanstack-query-react/solutions/02_query_configuration/src/components/IssueDetail.tsx
import { useIssue } from '../queries/issues';

interface IssueDetailProps {
  id: number | null;
}

export function IssueDetail({ id }: IssueDetailProps) {
  // Called before any early return: hooks run in the same order on every render.
  const { data: issue, error } = useIssue(id);

  if (id === null) {
    return (
      <aside className="detail">
        <p className="muted" data-testid="detail-empty">
          Select an issue to see its details.
        </p>
      </aside>
    );
  }

  return (
    <aside className="detail">
      {error ? (
        <p className="error">{error.message}</p>
      ) : !issue ? (
        // Only when no list holds the issue: the placeholder covers the rest.
        <p className="muted">Loading…</p>
      ) : (
        <>
          <h2 data-testid="detail-title">
            #{issue.id} {issue.title}
          </h2>
          <p className="muted">
            {issue.status} · {issue.assignee ?? 'unassigned'} · {issue.commentCount} comment(s)
          </p>
          {/* A placeholder is a summary: no description until the real issue lands. */}
          {'description' in issue ? (
            <p data-testid="detail-description">{issue.description}</p>
          ) : (
            <p className="muted">Loading the description…</p>
          )}
        </>
      )}
    </aside>
  );
}

// tanstack-query-angular/workshops/02_query_configuration/src/app/issues/issue-detail.ts
import { Component, input } from '@angular/core';
import { injectQuery } from '@tanstack/angular-query-experimental';
import { issueDetailQuery } from './issue-queries';

@Component({
  selector: 'app-issue-detail',
  template: `
    <aside class="detail">
      @if (issueId() === undefined) {
        <p class="muted" data-testid="detail-empty">Select an issue to see its details.</p>
      } @else if (detail.data(); as issue) {
        <h2 data-testid="detail-title">#{{ issue.id }} {{ issue.title }}</h2>
        <p class="muted">{{ issue.status }} · {{ issue.assignee ?? 'unassigned' }} · {{ issue.commentCount }} comment(s)</p>
        <!-- TODO (step 3): while the data is a placeholder (isPlaceholderData()),
             there is no description to show yet. -->
        <p data-testid="detail-description">{{ issue.description }}</p>
      } @else if (detail.isError()) {
        <p class="error">{{ detail.error().message }}</p>
      } @else {
        <p class="muted">Loading…</p>
      }
    </aside>
  `,
})
export class IssueDetail {
  readonly issueId = input<number>();

  // The `as number` silences TypeScript, not the request: with nothing
  // selected, this sends `GET /issues/undefined`. Read the Network panel.
  // TODO (step 2): no request at all until an issue is selected.
  // TODO (step 3): `placeholderData` — the summary from the list cache, so the
  // title shows at once. Why not `initialData`?
  protected readonly detail = injectQuery(() => issueDetailQuery(this.issueId() as number));
}
