// tanstack-query-angular/workshops/04_mutations/src/app/issues/issue-list.ts
import { Component, signal } from '@angular/core';
import { injectQuery } from '@tanstack/angular-query-experimental';
import { deleteIssue, type IssueFilter } from '../../api/fakeApi';
import { issuesQuery } from './issue-queries';

@Component({
  selector: 'app-issue-list',
  template: `
    <section>
      <div class="toolbar" role="group" aria-label="Filter">
        @for (option of filters; track option) {
          <button
            type="button"
            [attr.data-testid]="'filter-' + option"
            [attr.aria-pressed]="filter() === option"
            (click)="filter.set(option)"
          >
            {{ option }}
          </button>
        }
        @if (issues.isFetching() && !issues.isPending()) {
          <span class="muted" data-testid="list-refreshing">Refreshing…</span>
        }
      </div>

      @if (issues.isPending()) {
        <p class="muted" data-testid="list-loading">Loading…</p>
      } @else if (issues.isError()) {
        <p class="error" data-testid="list-error">{{ issues.error().message }}</p>
      } @else {
        <ul>
          @for (issue of issues.data(); track issue.id) {
            <li [attr.data-testid]="'issue-' + issue.id">
              <span class="muted">#{{ issue.id }}</span> {{ issue.title }}
              <button type="button" [attr.data-testid]="'delete-' + issue.id" (click)="remove(issue.id)">
                Delete
              </button>
            </li>
          }
        </ul>
      }
    </section>
  `,
})
export class IssueList {
  protected readonly filters: readonly IssueFilter[] = ['open', 'closed', 'all'];
  protected readonly filter = signal<IssueFilter>('open');

  protected readonly issues = injectQuery(() => issuesQuery(this.filter()));

  // TODO (step 4): `protected readonly deleteIssue = injectDeleteIssue();`,
  // and `deleteIssue.mutate(issue.id)` in the template.
  protected async remove(id: number): Promise<void> {
    // Deleted on the server — and still on screen, until a refetch nobody asks for.
    await deleteIssue(id);
  }
}

// tanstack-query-vue/workshops/04_mutations/src/components/IssueList.vue
<script setup lang="ts">
import { useQuery } from '@tanstack/vue-query';
import { deleteIssue } from '@/api/fakeApi';
import { issuesQuery } from '@/queries/issues';

const { data: issues, isPending, isFetching, error } = useQuery(issuesQuery('open'));

// TODO (step 4) — `useDeleteIssue()`, and disable the row being deleted
// (`isPending` and `variables`). Today the server deletes the issue, and the
// cache never hears of it: the row stays, the counter lies.
function remove(id: number): void {
  deleteIssue(id).catch(() => {
    // Swallowed: nobody tells the user.
  });
}
</script>

<template>
  <section>
    <div class="row spread">
      <h2>Open issues</h2>
      <span v-if="isFetching && !isPending" class="muted" data-testid="list-refreshing">refreshing…</span>
    </div>

    <p v-if="isPending" class="muted" data-testid="list-loading">Loading…</p>
    <p v-else-if="error" class="error" data-testid="list-error">{{ error.message }}</p>
    <ul v-else class="issues">
      <li v-for="issue in issues" :key="issue.id" :data-testid="`issue-${issue.id}`">
        <span>#{{ issue.id }} {{ issue.title }}</span>
        <button type="button" :data-testid="`delete-${issue.id}`" @click="remove(issue.id)">Delete</button>
      </li>
    </ul>
  </section>
</template>
