// tanstack-query-react/workshops/04_mutations/src/components/NewIssueForm.tsx
import { useState, type FormEvent } from 'react';
import { createIssue } from '../api/fakeApi';

export function NewIssueForm() {
  const [title, setTitle] = useState('');

  // TODO (step 1): `const { mutate, isPending, error } = useCreateIssue();` —
  // and this component no longer imports anything from '../api/fakeApi'.
  async function submit(event: FormEvent<HTMLFormElement>): Promise<void> {
    event.preventDefault();
    // The server creates the issue… and nobody else hears about it: the list
    // and the counter keep what they had in the cache. A refused write throws,
    // and nothing shows it.
    // TODO (step 2): `mutate({ title }, { onSuccess: () => setTitle('') })` —
    // clear the input only once the server accepted.
    await createIssue({ title });
    setTitle('');
  }

  return (
    <form className="row" onSubmit={(event) => void submit(event)}>
      <input
        aria-label="Title of the new issue"
        placeholder="Title of the new issue"
        data-testid="new-title"
        value={title}
        onChange={(event) => setTitle(event.target.value)}
      />
      {/* TODO (step 3): disabled while `isPending`. */}
      <button type="submit" data-testid="create-submit">
        Create
      </button>
      {/* TODO (step 2): `error.message` in a <p className="error" data-testid="create-error">. */}
    </form>
  );
}

// tanstack-query-vue/workshops/04_mutations/src/components/NewIssueForm.vue
<script setup lang="ts">
import { ref } from 'vue';
import { createIssue } from '@/api/fakeApi';

const title = ref('');

// TODO (step 1) — `useCreateIssue()` instead of calling the API by hand. Today
// the issue IS created on the server, and nothing on screen knows: the list
// does not show it, the counter in the header keeps lying.
// TODO (step 2) — `mutate(variables, { onSuccess })`: clear the input there,
// and only there. Show `error.message` in `create-error`.
// TODO (step 3) — disable `create-submit` while `isPending`.
async function submit(): Promise<void> {
  const input = { title: title.value };
  // Cleared BEFORE the server answered: a refused write loses what was typed.
  title.value = '';
  try {
    await createIssue(input);
  } catch {
    // Swallowed: nobody tells the user.
  }
}
</script>

<template>
  <form class="form" @submit.prevent="submit">
    <input v-model="title" data-testid="new-title" placeholder="Title of the new issue" aria-label="Title" />
    <button type="submit" data-testid="create-submit">Create</button>
  </form>
  <!-- TODO (step 2) — <p class="error" data-testid="create-error">…</p> -->
</template>
