// tanstack-query-react/solutions/06_testing/src/components/NewIssueForm.tsx
import { useState, type FormEvent } from 'react';
import { useCreateIssue } from '../queries/issues';

export function NewIssueForm() {
  const [title, setTitle] = useState('');
  const { mutate, isPending, error } = useCreateIssue();

  function submit(event: FormEvent<HTMLFormElement>): void {
    event.preventDefault();
    // Two kinds of callbacks. The hook's `onSuccess` (in queries/issues.ts)
    // keeps the CACHE right, whoever calls it. This one is about THIS form:
    // clear the input once the server accepted — a refused write keeps what
    // the user typed. It only runs if the component is still mounted.
    mutate({ title }, { onSuccess: () => setTitle('') });
  }

  return (
    <form className="row" onSubmit={submit}>
      <input
        aria-label="Title of the new issue"
        placeholder="Title of the new issue"
        data-testid="new-title"
        value={title}
        onChange={(event) => setTitle(event.target.value)}
      />
      {/* `isPending` — no `useState` to keep in sync by hand. */}
      <button type="submit" data-testid="create-submit" disabled={isPending}>
        {isPending ? 'Creating…' : 'Create'}
      </button>
      {/* Reset on the next `mutate`: a new attempt starts without the old error. */}
      {error && (
        <p className="error" data-testid="create-error">
          {error.message}
        </p>
      )}
    </form>
  );
}

// tanstack-query-vue/solutions/04_mutations/src/components/NewIssueForm.vue
<script setup lang="ts">
import { ref } from 'vue';
import { useCreateIssue } from '@/queries/issues';

const title = ref('');

const { mutate: create, isPending, error } = useCreateIssue();

function submit(): void {
  create(
    { title: title.value },
    {
      // The callbacks of `mutate()` run AFTER those of `useMutation`, and only
      // if this component is still mounted: the place for what concerns THIS
      // screen. The input is cleared once the server accepted the issue — a
      // refused write keeps what the user typed.
      onSuccess: () => {
        title.value = '';
      },
    },
  );
}
</script>

<template>
  <form class="form" @submit.prevent="submit">
    <input v-model="title" data-testid="new-title" placeholder="Title of the new issue" aria-label="Title" />
    <!-- `isPending` from the mutation: no double submit, no flag to reset. -->
    <button type="submit" data-testid="create-submit" :disabled="isPending">
      {{ isPending ? 'Creating…' : 'Create' }}
    </button>
  </form>
  <!-- `error` is reset as soon as the next `mutate()` starts. -->
  <p v-if="error" class="error" data-testid="create-error">{{ error.message }}</p>
</template>
