// tanstack-query-angular/workshops/06_testing/src/app/issues/new-issue-form.ts
import { Component, signal } from '@angular/core';
import { injectCreateIssue } from './issue-mutations';

@Component({
  selector: 'app-new-issue-form',
  template: `
    <form class="toolbar" (submit)="submit($event)">
      <input
        #titleInput
        data-testid="new-title"
        placeholder="What is broken?"
        aria-label="Title of the new issue"
        [value]="title()"
        (input)="title.set(titleInput.value)"
      />
      <!-- Pending until the lists have refetched: no double submit. -->
      <button type="submit" data-testid="create-submit" [disabled]="createIssue.isPending()">Create</button>
    </form>
    @if (createIssue.isError()) {
      <p class="error" data-testid="create-error">{{ createIssue.error().message }}</p>
    }
  `,
})
export class NewIssueForm {
  protected readonly title = signal('');
  protected readonly createIssue = injectCreateIssue();

  protected submit(event: Event): void {
    event.preventDefault();
    this.createIssue.mutate(this.title(), {
      // The callbacks of `mutate()` belong to THIS call, from THIS component:
      // the place for what only the form cares about. Clear the input on
      // success only — a refused write keeps what the user typed.
      onSuccess: () => this.title.set(''),
    });
  }
}

// tanstack-query-vue/solutions/04_mutations/src/components/NewIssueForm.vue
<script setup lang="ts">
import { ref } from 'vue';
import { useCreateIssue } from '@/queries/issues';

const title = ref('');

const { mutate: create, isPending, error } = useCreateIssue();

function submit(): void {
  create(
    { title: title.value },
    {
      // The callbacks of `mutate()` run AFTER those of `useMutation`, and only
      // if this component is still mounted: the place for what concerns THIS
      // screen. The input is cleared once the server accepted the issue — a
      // refused write keeps what the user typed.
      onSuccess: () => {
        title.value = '';
      },
    },
  );
}
</script>

<template>
  <form class="form" @submit.prevent="submit">
    <input v-model="title" data-testid="new-title" placeholder="Title of the new issue" aria-label="Title" />
    <!-- `isPending` from the mutation: no double submit, no flag to reset. -->
    <button type="submit" data-testid="create-submit" :disabled="isPending">
      {{ isPending ? 'Creating…' : 'Create' }}
    </button>
  </form>
  <!-- `error` is reset as soon as the next `mutate()` starts. -->
  <p v-if="error" class="error" data-testid="create-error">{{ error.message }}</p>
</template>
