// tanstack-query-angular/workshops/03_pagination_infinite/src/app/issues/issue-table.ts
import { Component, signal } from '@angular/core';
import { injectQuery } from '@tanstack/angular-query-experimental';
import { issuePageQuery } from './issue-queries';

@Component({
  selector: 'app-issue-table',
  template: `
    <section>
      <h2>All issues</h2>

      @if (issues.data(); as current) {
        <!-- TODO (step 1): dim the table while it shows the previous page (isPlaceholderData()). -->
        <table>
          <tbody>
            @for (issue of current.items; track issue.id) {
              <tr [attr.data-testid]="'issue-' + issue.id">
                <td class="muted">#{{ issue.id }}</td>
                <td>{{ issue.title }}</td>
                <td class="muted">{{ issue.status }}</td>
              </tr>
            }
          </tbody>
        </table>

        <div class="pager">
          <button type="button" data-testid="page-prev" [disabled]="page() === 1" (click)="page.set(page() - 1)">
            ← Previous
          </button>
          <span data-testid="page-indicator">Page {{ current.page }} / {{ current.totalPages }}</span>
          <!-- TODO (step 1): also disabled while the next page is not there yet. -->
          <button
            type="button"
            data-testid="page-next"
            [disabled]="current.page >= current.totalPages"
            (click)="page.set(page() + 1)"
          >
            Next →
          </button>
        </div>
      } @else if (issues.isError()) {
        <p class="error">{{ issues.error().message }}</p>
      } @else {
        <p class="muted" data-testid="issues-loading">Loading…</p>
      }
    </section>
  `,
})
export class IssueTable {
  protected readonly page = signal(1);

  // Every page is a new key, so a new cache entry with nothing in it: the table
  // empties and "Loading…" comes back at every click.
  // TODO (step 1): keep the previous page on screen — `placeholderData: keepPreviousData`.
  protected readonly issues = injectQuery(() => issuePageQuery(this.page()));

  // TODO (step 2): whenever a real page is on screen, prefetch the next one
  // with `queryClient.prefetchQuery(...)` — in an `effect()` of the constructor,
  // with `inject(QueryClient)` as a field.
}

// tanstack-query-react/workshops/03_pagination_infinite/src/components/IssueTable.tsx
import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { issuePageQuery } from '../queries/issues';

export function IssueTable() {
  const [page, setPage] = useState(1);

  // TODO (step 1): page 2 is a NEW key, so `data` is undefined — and the table
  // empty — until it arrives. Spread `issuePageQuery(page)` into an object with
  // `placeholderData: keepPreviousData`, and read `isPlaceholderData` too.
  const { data, isPending, error } = useQuery(issuePageQuery(page));

  const totalPages = data?.totalPages ?? 1;
  const hasNext = page < totalPages;

  // TODO (step 2): as soon as a page is REALLY on screen (not a placeholder),
  // prefetch the next one in an effect:
  // `queryClient.prefetchQuery(issuePageQuery(page + 1))`, with
  // `const queryClient = useQueryClient()`.

  return (
    <section>
      <h2>All issues</h2>

      {error ? (
        <p className="error">{error.message}</p>
      ) : isPending ? (
        <p className="muted" data-testid="issues-loading">
          Loading…
        </p>
      ) : (
        // TODO (step 1): add the `dimmed` class while `isPlaceholderData`.
        <table className="issues-table">
          <tbody>
            {data.items.map((issue) => (
              <tr key={issue.id} data-testid={`issue-${issue.id}`}>
                <td>#{issue.id}</td>
                <td className={issue.status === 'closed' ? 'closed' : undefined}>{issue.title}</td>
                <td className="muted">{issue.assignee ?? 'unassigned'}</td>
              </tr>
            ))}
          </tbody>
        </table>
      )}

      <div className="row">
        <button type="button" data-testid="page-prev" disabled={page === 1} onClick={() => setPage((p) => p - 1)}>
          Previous
        </button>
        <span data-testid="page-indicator">
          Page {page} / {totalPages}
        </span>
        {/* TODO (step 1): also disabled while `isPlaceholderData`. */}
        <button type="button" data-testid="page-next" disabled={!hasNext} onClick={() => setPage((p) => p + 1)}>
          Next
        </button>
      </div>
    </section>
  );
}
