// vuejs-advanced/workshops/17_tanstack_query/src/components/NewIssueForm.vue
<script setup lang="ts">
import { ref } from 'vue';
import { createIssue } from '@/api/fakeApi';

const emit = defineEmits<{ created: [] }>();

// TODO 3.2 — replace with `useCreateIssue()`: `mutate`, `isPending` and
// `error` come from the mutation, and the cache refreshes EVERY list — the
// header counter included — without anyone listening to an event.
const title = ref('');
const submitting = ref(false);
const submitError = ref<Error | null>(null);

async function submit(): Promise<void> {
  submitting.value = true;
  submitError.value = null;
  try {
    await createIssue(title.value);
    title.value = '';
    emit('created');
  } catch (e) {
    submitError.value = e as Error;
  } finally {
    submitting.value = false;
  }
}
</script>

<template>
  <form class="row" @submit.prevent="submit">
    <input v-model="title" data-testid="new-title" placeholder="A new issue" aria-label="Issue title" />
    <button type="submit" data-testid="create" :disabled="submitting">
      {{ submitting ? 'Creating…' : 'Create' }}
    </button>
    <p v-if="submitError" class="error">{{ submitError.message }}</p>
  </form>
</template>

// tanstack-query-react/workshops/04_mutations/src/components/NewIssueForm.tsx
import { useState, type FormEvent } from 'react';
import { createIssue } from '../api/fakeApi';

export function NewIssueForm() {
  const [title, setTitle] = useState('');

  // TODO (step 1): `const { mutate, isPending, error } = useCreateIssue();` —
  // and this component no longer imports anything from '../api/fakeApi'.
  async function submit(event: FormEvent<HTMLFormElement>): Promise<void> {
    event.preventDefault();
    // The server creates the issue… and nobody else hears about it: the list
    // and the counter keep what they had in the cache. A refused write throws,
    // and nothing shows it.
    // TODO (step 2): `mutate({ title }, { onSuccess: () => setTitle('') })` —
    // clear the input only once the server accepted.
    await createIssue({ title });
    setTitle('');
  }

  return (
    <form className="row" onSubmit={(event) => void submit(event)}>
      <input
        aria-label="Title of the new issue"
        placeholder="Title of the new issue"
        data-testid="new-title"
        value={title}
        onChange={(event) => setTitle(event.target.value)}
      />
      {/* TODO (step 3): disabled while `isPending`. */}
      <button type="submit" data-testid="create-submit">
        Create
      </button>
      {/* TODO (step 2): `error.message` in a <p className="error" data-testid="create-error">. */}
    </form>
  );
}
