// tanstack-query-angular/solutions/02_query_configuration/src/app/app.ts
import { Component, signal } from '@angular/core';
import { IssueDetail } from './issues/issue-detail';
import { IssueList } from './issues/issue-list';
import { OpenCount } from './issues/open-count';

@Component({
  selector: 'app-root',
  imports: [IssueDetail, IssueList, OpenCount],
  template: `
    <header class="app-header">
      <h1>Issue tracker</h1>
      <app-open-count />
    </header>
    <main class="columns">
      <app-issue-list (selected)="selectedId.set($event)" />
      <app-issue-detail [issueId]="selectedId()" />
    </main>
  `,
})
export class App {
  // Client state — which issue is selected — stays a plain signal. Only the
  // SERVER state goes through TanStack Query.
  protected readonly selectedId = signal<number | undefined>(undefined);
}

// tanstack-query-react/solutions/02_query_configuration/src/App.tsx
import { useState } from 'react';
import { IssueCounter } from './components/IssueCounter';
import { IssueDetail } from './components/IssueDetail';
import { IssueList } from './components/IssueList';

export function App() {
  // Client state — which issue the user looks at — stays in React. Only the
  // server state goes to the cache.
  const [selectedId, setSelectedId] = useState<number | null>(null);

  return (
    <>
      <header className="header">
        <h1>Issue tracker</h1>
        <IssueCounter />
      </header>
      <main className="columns">
        <IssueList selectedId={selectedId} onSelect={setSelectedId} />
        <IssueDetail id={selectedId} />
      </main>
    </>
  );
}
