// tanstack-query-react/solutions/05_optimistic_updates/src/components/NewIssueForm.tsx
import { useState, type FormEvent } from 'react';
import { useCreateIssue } from '../queries/issues';

export function NewIssueForm() {
  const [title, setTitle] = useState('');
  const { mutate, isPending, variables, error } = useCreateIssue();

  function submit(event: FormEvent<HTMLFormElement>): void {
    event.preventDefault();
    mutate({ title }, { onSuccess: () => setTitle('') });
  }

  return (
    <>
      {/* Optimistic through the UI: no id yet, no cache write — just what the
          user sent, greyed out, while the mutation is pending. Nothing to roll
          back: once it settles, the row is gone, and the real one (or the error)
          is there. */}
      {isPending && (
        <ul className="issues">
          <li className="pending" data-testid="pending-issue">
            <span>{variables.title}</span>
            <span className="muted">creating…</span>
          </li>
        </ul>
      )}

      <form className="row" onSubmit={submit}>
        <input
          aria-label="Title of the new issue"
          placeholder="Title of the new issue"
          data-testid="new-title"
          value={title}
          onChange={(event) => setTitle(event.target.value)}
        />
        <button type="submit" data-testid="create-submit" disabled={isPending}>
          {isPending ? 'Creating…' : 'Create'}
        </button>
        {error && (
          <p className="error" data-testid="create-error">
            {error.message}
          </p>
        )}
      </form>
    </>
  );
}

// tanstack-query-vue/solutions/05_optimistic_updates/src/components/NewIssueForm.vue
<script setup lang="ts">
import { ref } from 'vue';
import { useCreateIssue } from '@/queries/issues';

const title = ref('');

// `variables`: what the last `mutate()` received — here, the title being
// created. Shown while `isPending`, it IS the optimistic row: no cache write,
// so nothing to roll back. On failure it just disappears, and the error shows.
const { mutate: create, isPending, variables, error } = useCreateIssue();

function submit(): void {
  create(
    { title: title.value },
    {
      onSuccess: () => {
        title.value = '';
      },
    },
  );
}
</script>

<template>
  <ul v-if="isPending && variables" class="issues">
    <li class="pending" data-testid="pending-issue">
      <span>{{ variables.title }}</span>
      <span>saving…</span>
    </li>
  </ul>
  <form class="form" @submit.prevent="submit">
    <input v-model="title" data-testid="new-title" placeholder="Title of the new issue" aria-label="Title" />
    <button type="submit" data-testid="create-submit" :disabled="isPending">Create</button>
  </form>
  <p v-if="error" class="error" data-testid="create-error">{{ error.message }}</p>
</template>
