// tanstack-query-react/solutions/01_first_queries/src/App.tsx
import { IssueCounter } from './components/IssueCounter';
import { IssueList } from './components/IssueList';

export function App() {
  return (
    <>
      <header className="header">
        <h1>Issue tracker</h1>
        <IssueCounter />
      </header>
      <main>
        <IssueList />
      </main>
    </>
  );
}

// tanstack-query-angular/workshops/01_first_queries/src/app/app.ts
import { Component } from '@angular/core';
import { IssueList } from './issues/issue-list';
import { OpenCount } from './issues/open-count';

@Component({
  selector: 'app-root',
  imports: [IssueList, OpenCount],
  template: `
    <header class="app-header">
      <h1>Issue tracker</h1>
      <app-open-count />
    </header>
    <main>
      <app-issue-list />
    </main>
  `,
})
export class App {}
