// tanstack-query-react/workshops/03_pagination_infinite/src/components/ActivityFeed.tsx
import { useQuery } from '@tanstack/react-query';
import { activityFirstPageQuery } from '../queries/activity';

export function ActivityFeed() {
  // TODO (step 3): `useInfiniteQuery(activityFeedQuery)`, then read `data.pages`,
  // `fetchNextPage`, `hasNextPage` and `isFetchingNextPage` from it.
  const { data, isPending, error } = useQuery(activityFirstPageQuery);

  return (
    <section>
      <h2>Activity</h2>

      {error ? (
        <p className="error">{error.message}</p>
      ) : isPending ? (
        <p className="muted">Loading…</p>
      ) : (
        <ul className="feed">
          {/* TODO (step 3): every item of every page — `data.pages.flatMap(…)`. */}
          {data.items.map((event) => (
            <li key={event.id} data-testid={`activity-${event.id}`}>
              {event.message}
            </li>
          ))}
        </ul>
      )}

      {/* TODO (step 3): show `activity-loading-more` while the next page loads
          (`isFetchingNextPage`), and the button only when `hasNextPage`. */}
      <button
        type="button"
        data-testid="load-more"
        onClick={() => {
          // TODO (step 3): `void fetchNextPage()`.
        }}
      >
        Load more
      </button>
    </section>
  );
}

// tanstack-query-angular/workshops/03_pagination_infinite/src/app/activity/activity-feed.ts
import { Component } from '@angular/core';
import { injectQuery } from '@tanstack/angular-query-experimental';
import { activityFeedQuery } from './activity-queries';

@Component({
  selector: 'app-activity-feed',
  template: `
    <section>
      <h2>Activity</h2>

      @if (feed.data(); as page) {
        <!-- TODO (step 3): one entry per page loaded — data().pages — each with its items. -->
        <ul>
          @for (event of page.items; track event.id) {
            <li [attr.data-testid]="'activity-' + event.id">{{ event.message }}</li>
          }
        </ul>

        <!-- TODO (step 3): <p data-testid="activity-loading-more"> while the next page loads. -->
        <!-- TODO (step 3): no button at all when there is nothing more to load. -->
        <button type="button" data-testid="load-more" (click)="loadMore()">Load more</button>
      } @else if (feed.isError()) {
        <p class="error">{{ feed.error().message }}</p>
      } @else {
        <p class="muted">Loading…</p>
      }
    </section>
  `,
})
export class ActivityFeed {
  // TODO (step 3): `injectInfiniteQuery(() => activityFeedQuery())`.
  protected readonly feed = injectQuery(() => activityFeedQuery());

  protected loadMore(): void {
    // TODO (step 3): `this.feed.fetchNextPage()` — once the feed is an infinite query.
  }
}
