// tanstack-query-react/workshops/01_first_queries/src/components/IssueCounter.tsx
import { useEffect, useState } from 'react';
import { fetchIssues } from '../api/fakeApi';

/**
 * The header counter, fetching the way most apps start: an effect and a piece
 * of state. It needs the open issues — and so does the list, which fetches its
 * own copy. Two components, two requests for the same data.
 */
export function IssueCounter() {
  const [count, setCount] = useState<number | null>(null);

  // TODO (step 2): replace this effect and this state with
  // `useQuery(issuesQuery('open'))`, and show `data.length`.
  useEffect(() => {
    fetchIssues('open')
      .then((issues) => setCount(issues.length))
      .catch(() => setCount(null));
  }, []);

  return (
    <span className="counter" data-testid="open-count">
      {count ?? '…'} open
    </span>
  );
}

// vuejs-advanced/workshops/17_tanstack_query/src/components/IssueCounter.vue
<script setup lang="ts">
import { onMounted, ref } from 'vue';
import { fetchIssues } from '@/api/fakeApi';

// TODO 1.4 — replace this hand-rolled fetch with `useQuery(issuesQuery('open'))`,
// and a `select` that turns the cached list into its length. Same key as the
// list's default filter: the two components share ONE request and ONE cache
// entry.
const count = ref<number | null>(null);

onMounted(async () => {
  count.value = (await fetchIssues('open')).length;
});
</script>

<template>
  <span class="badge" data-testid="open-count">
    {{ count ?? '…' }} open
  </span>
</template>
