// tanstack-query-react/workshops/02_query_configuration/src/components/IssueCounter.tsx
import { useQuery } from '@tanstack/react-query';
import { issuesQuery } from '../queries/issues';

/**
 * The header counter. Same key as the open list: one entry of the cache, one
 * request, two components.
 */
export function IssueCounter() {
  // TODO (step 4): other users close issues too. Once `staleTime` is 30 s, a
  // focus refetches nothing for 30 s — add `refetchOnWindowFocus: 'always'` to
  // THIS query only: `useQuery({ ...issuesQuery('open'), refetchOnWindowFocus: 'always' })`.
  // (Bonus) `select: (issues) => issues.length`.
  const { data: issues } = useQuery(issuesQuery('open'));

  return (
    <span className="counter" data-testid="open-count">
      {issues ? issues.length : '…'} open
    </span>
  );
}

// vuejs-advanced/workshops/17_tanstack_query/src/components/IssueCounter.vue
<script setup lang="ts">
import { onMounted, ref } from 'vue';
import { fetchIssues } from '@/api/fakeApi';

// TODO 1.4 — replace this hand-rolled fetch with `useQuery(issuesQuery('open'))`,
// and a `select` that turns the cached list into its length. Same key as the
// list's default filter: the two components share ONE request and ONE cache
// entry.
const count = ref<number | null>(null);

onMounted(async () => {
  count.value = (await fetchIssues('open')).length;
});
</script>

<template>
  <span class="badge" data-testid="open-count">
    {{ count ?? '…' }} open
  </span>
</template>
