// tanstack-query-react/solutions/03_pagination_infinite/src/components/ActivityFeed.tsx
import { useInfiniteQuery } from '@tanstack/react-query';
import { activityFeedQuery } from '../queries/activity';

export function ActivityFeed() {
  const { data, isPending, error, fetchNextPage, hasNextPage, isFetchingNextPage } =
    useInfiniteQuery(activityFeedQuery);

  return (
    <section>
      <h2>Activity</h2>

      {error ? (
        <p className="error">{error.message}</p>
      ) : isPending ? (
        <p className="muted">Loading…</p>
      ) : (
        <ul className="feed">
          {/* `data.pages` holds every page loaded so far, in order. */}
          {data.pages.flatMap((page) =>
            page.items.map((event) => (
              <li key={event.id} data-testid={`activity-${event.id}`}>
                {event.message}
              </li>
            )),
          )}
        </ul>
      )}

      {isFetchingNextPage && (
        <p className="muted" data-testid="activity-loading-more">
          Loading more…
        </p>
      )}
      {/* No next page, no button: the last page said `nextCursor: null`. */}
      {hasNextPage && (
        <button
          type="button"
          data-testid="load-more"
          disabled={isFetchingNextPage}
          onClick={() => void fetchNextPage()}
        >
          Load more
        </button>
      )}
    </section>
  );
}

// tanstack-query-angular/solutions/03_pagination_infinite/src/app/activity/activity-feed.ts
import { Component } from '@angular/core';
import { injectInfiniteQuery } from '@tanstack/angular-query-experimental';
import { activityFeedQuery } from './activity-queries';

@Component({
  selector: 'app-activity-feed',
  template: `
    <section>
      <h2>Activity</h2>

      @if (feed.isPending()) {
        <p class="muted">Loading…</p>
      } @else if (feed.isError()) {
        <p class="error">{{ feed.error().message }}</p>
      } @else {
        <ul>
          <!-- data().pages: one entry per page loaded, in order — appended, never replaced. -->
          @for (page of feed.data().pages; track $index) {
            @for (event of page.items; track event.id) {
              <li [attr.data-testid]="'activity-' + event.id">{{ event.message }}</li>
            }
          }
        </ul>

        @if (feed.isFetchingNextPage()) {
          <p class="muted" data-testid="activity-loading-more">Loading more…</p>
        }
        <!-- No button at all once getNextPageParam returned undefined. -->
        @if (feed.hasNextPage()) {
          <button
            type="button"
            data-testid="load-more"
            [disabled]="feed.isFetchingNextPage()"
            (click)="feed.fetchNextPage()"
          >
            Load more
          </button>
        }
      }
    </section>
  `,
})
export class ActivityFeed {
  protected readonly feed = injectInfiniteQuery(() => activityFeedQuery());
}
