// tanstack-query-angular/solutions/03_pagination_infinite/src/app/app.ts
import { Component } from '@angular/core';
import { ActivityFeed } from './activity/activity-feed';
import { IssueTable } from './issues/issue-table';

@Component({
  selector: 'app-root',
  imports: [ActivityFeed, IssueTable],
  template: `
    <header class="app-header">
      <h1>Issue tracker</h1>
    </header>
    <main class="columns">
      <app-issue-table />
      <app-activity-feed />
    </main>
  `,
})
export class App {}

// tanstack-query-react/solutions/03_pagination_infinite/src/App.tsx
import { ActivityFeed } from './components/ActivityFeed';
import { IssueTable } from './components/IssueTable';

export function App() {
  return (
    <>
      <header className="header">
        <h1>Issue tracker</h1>
      </header>
      <main className="columns">
        <IssueTable />
        <ActivityFeed />
      </main>
    </>
  );
}
