// tanstack-query-react/solutions/05_optimistic_updates/src/components/IssueList.tsx
import { useQuery } from '@tanstack/react-query';
import type { IssueSummary } from '../api/fakeApi';
import { issuesQuery, useSetIssueStatus } from '../queries/issues';
import { NewIssueForm } from './NewIssueForm';

export function IssueList() {
  const { data: issues, isPending, error } = useQuery(issuesQuery('open'));
  const statusChange = useSetIssueStatus();

  function toggle(issue: IssueSummary): void {
    statusChange.mutate({ id: issue.id, status: issue.status === 'open' ? 'closed' : 'open' });
  }

  return (
    <section>
      <h2>Open issues</h2>

      {/* Shown after the rollback: the issue is back, and the user is told why. */}
      {statusChange.error && (
        <p className="error" data-testid="toggle-error">
          {statusChange.error.message}
        </p>
      )}

      {error ? (
        <p className="error" data-testid="list-error">
          {error.message}
        </p>
      ) : isPending ? (
        <p className="muted" data-testid="list-loading">
          Loading…
        </p>
      ) : (
        <ul className="issues">
          {issues.map((issue) => (
            <li key={issue.id} data-testid={`issue-${issue.id}`}>
              <span>
                #{issue.id} {issue.title}
              </span>
              <button type="button" data-testid={`toggle-${issue.id}`} onClick={() => toggle(issue)}>
                {issue.status === 'open' ? 'Close' : 'Reopen'}
              </button>
            </li>
          ))}
        </ul>
      )}

      <NewIssueForm />
    </section>
  );
}

// tanstack-query-vue/workshops/05_optimistic_updates/src/components/IssueList.vue
<script setup lang="ts">
import { ref } from 'vue';
import { useQuery } from '@tanstack/vue-query';
import type { IssueFilter, IssueSummary } from '@/api/fakeApi';
import { FILTERS, issuesQuery, useToggleIssue } from '@/queries/issues';

const filter = ref<IssueFilter>('open');

const { data: issues, isPending, isFetching, error } = useQuery(() => issuesQuery(filter.value));

// The component only says WHAT changes. How the cache follows — and how it
// comes back — is the composable's business.
const { mutate: setStatus, error: toggleError } = useToggleIssue();

function toggle(issue: IssueSummary): void {
  setStatus({ id: issue.id, status: issue.status === 'open' ? 'closed' : 'open' });
}
</script>

<template>
  <section>
    <div class="row spread">
      <div class="row">
        <button
          v-for="option in FILTERS"
          :key="option"
          type="button"
          :aria-pressed="filter === option"
          :data-testid="`filter-${option}`"
          @click="filter = option"
        >
          {{ option }}
        </button>
      </div>
      <span v-if="isFetching && !isPending" class="muted" data-testid="list-refreshing">refreshing…</span>
    </div>

    <p v-if="toggleError" class="error" data-testid="toggle-error">{{ toggleError.message }}</p>
    <p v-if="isPending" class="muted" data-testid="list-loading">Loading…</p>
    <p v-else-if="error" class="error" data-testid="list-error">{{ error.message }}</p>
    <ul v-else class="issues">
      <li v-for="issue in issues" :key="issue.id" :data-testid="`issue-${issue.id}`">
        <span :class="{ closed: issue.status === 'closed' }">#{{ issue.id }} {{ issue.title }}</span>
        <button type="button" :data-testid="`toggle-${issue.id}`" @click="toggle(issue)">
          {{ issue.status === 'open' ? 'Close' : 'Reopen' }}
        </button>
      </li>
    </ul>
  </section>
</template>
