// tanstack-query-react/workshops/05_optimistic_updates/src/components/NewIssueForm.tsx
import { useState, type FormEvent } from 'react';
import { useCreateIssue } from '../queries/issues';

export function NewIssueForm() {
  const [title, setTitle] = useState('');
  const { mutate, isPending, error } = useCreateIssue();

  function submit(event: FormEvent<HTMLFormElement>): void {
    event.preventDefault();
    mutate({ title }, { onSuccess: () => setTitle('') });
  }

  return (
    <>
      {/* TODO (step 3): while `isPending`, show what the user sent — greyed out:
          <ul className="issues">
            <li className="pending" data-testid="pending-issue">{variables.title}</li>
          </ul> */}

      <form className="row" onSubmit={submit}>
        <input
          aria-label="Title of the new issue"
          placeholder="Title of the new issue"
          data-testid="new-title"
          value={title}
          onChange={(event) => setTitle(event.target.value)}
        />
        <button type="submit" data-testid="create-submit" disabled={isPending}>
          {isPending ? 'Creating…' : 'Create'}
        </button>
        {error && (
          <p className="error" data-testid="create-error">
            {error.message}
          </p>
        )}
      </form>
    </>
  );
}

// tanstack-query-vue/workshops/05_optimistic_updates/src/components/NewIssueForm.vue
<script setup lang="ts">
import { ref } from 'vue';
import { useCreateIssue } from '@/queries/issues';

const title = ref('');

// TODO (step 3) — also take `variables`, and show it as `pending-issue` (the
// title, greyed out) while `isPending`. Today, nothing shows up until the POST
// AND the refetch are back.
const { mutate: create, isPending, error } = useCreateIssue();

function submit(): void {
  create(
    { title: title.value },
    {
      onSuccess: () => {
        title.value = '';
      },
    },
  );
}
</script>

<template>
  <!-- TODO (step 3) —
  <ul class="issues">
    <li class="pending" data-testid="pending-issue">…the title being created…</li>
  </ul> -->
  <form class="form" @submit.prevent="submit">
    <input v-model="title" data-testid="new-title" placeholder="Title of the new issue" aria-label="Title" />
    <button type="submit" data-testid="create-submit" :disabled="isPending">Create</button>
  </form>
  <p v-if="error" class="error" data-testid="create-error">{{ error.message }}</p>
</template>
