// tanstack-query-react/workshops/01_first_queries/src/components/IssueList.tsx
import { useEffect, useState } from 'react';
import { fetchIssues, type IssueFilter, type IssueSummary } from '../api/fakeApi';

const FILTERS: IssueFilter[] = ['open', 'closed', 'all'];

export function IssueList() {
  const [filter, setFilter] = useState<IssueFilter>('open');

  // TODO (step 2): three pieces of state, an effect and a try/finally — all of
  // it becomes ONE `useQuery(issuesQuery(filter))` (step 3: the key follows
  // `filter`). Read `data`, `isPending`, `isFetching` and `error` from it.
  const [issues, setIssues] = useState<IssueSummary[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<Error | null>(null);

  useEffect(() => {
    async function load() {
      // Every filter change starts from scratch: what was loaded a second ago
      // for this filter is gone, and "Loading…" shows again.
      setLoading(true);
      setError(null);
      try {
        // No way to ignore an answer that comes too late: a slow filter that
        // answers after a fast one overwrites it.
        setIssues(await fetchIssues(filter));
      } catch (caught) {
        setError(caught as Error);
      } finally {
        setLoading(false);
      }
    }
    void load();
  }, [filter]);

  return (
    <section>
      <div className="row" role="tablist" aria-label="Filter the issues">
        {FILTERS.map((option) => (
          <button
            key={option}
            type="button"
            role="tab"
            aria-selected={filter === option}
            data-testid={`filter-${option}`}
            onClick={() => setFilter(option)}
          >
            {option}
          </button>
        ))}
        {/* TODO (step 4): show this hint while a request is in flight BEHIND data
            already on screen — `isFetching && !isPending`. */}
      </div>

      {error ? (
        <p className="error" data-testid="list-error">
          {error.message}
        </p>
      ) : loading ? (
        // TODO (step 4): only while there is nothing to show yet — `isPending`.
        <p className="muted" data-testid="list-loading">
          Loading…
        </p>
      ) : (
        <ul className="issues">
          {issues.map((issue) => (
            <li key={issue.id} data-testid={`issue-${issue.id}`}>
              <span className={issue.status === 'closed' ? 'closed' : undefined}>
                #{issue.id} {issue.title}
              </span>
              <span className="muted">{issue.assignee ?? 'unassigned'}</span>
            </li>
          ))}
        </ul>
      )}
    </section>
  );
}

// tanstack-query-vue/workshops/01_first_queries/src/components/IssueList.vue
<script setup lang="ts">
import { ref, watch } from 'vue';
import { fetchIssues, type IssueFilter, type IssueSummary } from '@/api/fakeApi';

const FILTERS: IssueFilter[] = ['open', 'closed', 'all'];
const filter = ref<IssueFilter>('open');

// TODO (step 2) — replace these three refs and `load()` with `useQuery`.
// TODO (step 3) — …with a GETTER, `() => issuesQuery(filter.value)`, so the key
// follows the filter.
const issues = ref<IssueSummary[]>();
const loading = ref(false);
const error = ref<Error | null>(null);

// Three bugs, all visible in the Network panel:
// - this list and the header counter each send `GET /issues?status=open`;
// - coming back to a filter forgets what it had: "Loading…" again;
// - nothing tells an old answer from the current one — with a slow server, the
//   answer for the filter you LEFT can land last, and stay on screen.
async function load(current: IssueFilter): Promise<void> {
  loading.value = true;
  issues.value = undefined;
  error.value = null;
  try {
    issues.value = await fetchIssues(current);
  } catch (caught) {
    error.value = caught as Error;
  } finally {
    loading.value = false;
  }
}

watch(filter, load, { immediate: true });
</script>

<template>
  <section>
    <div class="row spread">
      <div class="row">
        <button
          v-for="option in FILTERS"
          :key="option"
          type="button"
          :aria-pressed="filter === option"
          :data-testid="`filter-${option}`"
          @click="filter = option"
        >
          {{ option }}
        </button>
      </div>
      <!-- TODO (step 4) — `list-refreshing`, while a request is in flight BEHIND
           data already on screen (`isFetching && !isPending`):
           <span class="muted" data-testid="list-refreshing">refreshing…</span> -->
    </div>

    <!-- TODO (step 4) — `isPending`, not "a request is in flight". -->
    <p v-if="loading" class="muted" data-testid="list-loading">Loading…</p>
    <p v-else-if="error" class="error" data-testid="list-error">{{ error.message }}</p>
    <ul v-else class="issues">
      <li v-for="issue in issues" :key="issue.id" :data-testid="`issue-${issue.id}`">
        <span :class="{ closed: issue.status === 'closed' }">#{{ issue.id }} {{ issue.title }}</span>
        <span class="muted">{{ issue.assignee ?? 'unassigned' }}</span>
      </li>
    </ul>
  </section>
</template>
